baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://yagopv.github.io

# Site settings
title: Yago Pérez Vázquez - Portfolio
email: yagoperez@outlook.com
description: "This is my portfolio. Here you can take a look to the main projects I get involved in."

# Team names, titles and social links
# people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/yagopv/?ppe=1
  - title: github
    url: http://github.com/yagopv    
  - title: twitter
    url: http://twitter.com/yperezva
  - title: facebook
    url: http://facebook.com/yawette

# Postal address (add as many lines as necessary)
address:
  - line: 15002
  - line: A Coruña, Spain

# Build settings
markdown: kramdown
permalink: pretty